apiVersion: 1

datasources:
  - name: MySQL-movilidad
    uid: mysql_movilidad
    type: mysql
    access: proxy
    url: mysql:3306
    database: movilidad
    user: app_reader
    isDefault: true
    jsonData:
      maxOpenConns: 50
      maxIdleConns: 10
      connMaxLifetime: 14400
      timeInterval: 10s
    secureJsonData:
      password: ${MYSQL_APP_READER_PASSWORD}

  - name: MySQL-metrics
    uid: mysql_metrics
    type: mysql
    access: proxy
    url: mysql:3306
    database: performance_schema
    user: db_metrics_reader
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      timeInterval: 10s
    secureJsonData:
      password: ${MYSQL_DB_METRICS_PASSWORD}
